#! /bin/bash
# TF_ADDRESS="https://registry-vpc.cn-shanghai.aliyuncs.com/api/v4/projects/terraform/state/terraform.tfstate" \

terraform init 
#\
#    -backend-config="address=registry-vpc.cn-shanghai.aliyuncs.com" \
#    -backend-config="path=example_app/terraform.tfstate" \
#    -backend-config="scheme=https"
