/*resource_location   = "#{AZR_Location}"
resource_group_name = "#{AZR_ResourceGroup}"
tag_appid           = "#{AZR_AppIDTag}"
tag_environment     = "#{AZR_EnvironmentTag}"
dns_domain_name     = "#{WebDNS}"
static_site_name    = "#{AZR_SWA}"
gh_repo_name        = "#{GH_Repository}"
gh_api_key          = "#{GH_API_KEY}"
servicenow_pass     = "#{SN_APIPass}"
servicenow_user     = "#{SN_APIUser}"
*/