name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions only"
 
on:
 push:
   branches:
   - main
 pull_request: {}
 
env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO

jobs:
 terraform:
   name: "Terraform Infrastructure Change Management"
   container: registry-vpc.cn-shanghai.aliyuncs.com/jllt-china/terraform:latest
 
   steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2

     - name: Terraform format
       id: fmt
       run: terraform fmt -check || echo true

     - name: Terraform init
       id: init
       run: terraform init

     - name: Terraform validate
       id: validate
       run: terraform validate

     - name: Terraform before access
       id: before access
       run: export TF_VAR_ALICLOUD_ACCESS_KEY=${ALICLOUD_ACCESS_KEY} 
     - name: Terraform before secret
       id: before secret
       run: export TF_VAR_ALICLOUD_SECRET_KEY=${ALICLOUD_SECRET_KEY}
 
     - name: Terraform plan
       id: plan
       if: github.event_name == 'push'
       run: terraform plan -no-color -input=false
       continue-on-error: true
